
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SALON = 7;
  public static final int PARENTESIS_ABRE = 14;
  public static final int HORARIO = 9;
  public static final int PARENTESIS_CIERRA = 15;
  public static final int ASIGNAR = 10;
  public static final int COMA = 12;
  public static final int NUMEROS = 3;
  public static final int EOF = 0;
  public static final int EDIFICIO = 6;
  public static final int COMILLA = 11;
  public static final int TEXTO = 16;
  public static final int error = 1;
  public static final int USUARIO = 4;
  public static final int ESTUDIANTE = 2;
  public static final int PUNTO_COMA = 13;
  public static final int CATEDRATICO = 5;
  public static final int COLABORADOR = 17;
  public static final int CURSO = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ESTUDIANTE",
  "NUMEROS",
  "USUARIO",
  "CATEDRATICO",
  "EDIFICIO",
  "SALON",
  "CURSO",
  "HORARIO",
  "ASIGNAR",
  "COMILLA",
  "COMA",
  "PUNTO_COMA",
  "PARENTESIS_ABRE",
  "PARENTESIS_CIERRA",
  "TEXTO",
  "COLABORADOR"
  };
}

